import { useEffect, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { supabase } from '../../lib/supabaseClient';
const pct=(n,d)=>d?`${(100*n/d).toFixed(1)}%`:'—';
function Table({title,values,total}){return <section className="bg-white rounded-xl border p-5"><h2 className="text-xl font-semibold mb-4">{title}</h2>{!Object.keys(values).length?<p>No recorded activity yet.</p>:<table className="w-full text-left text-sm"><thead><tr><th className="py-2">Item</th><th>Visits</th><th>Reach</th></tr></thead><tbody>{Object.entries(values).map(([k,v])=><tr key={k} className="border-t"><td className="py-2">{k}</td><td>{v}</td><td>{pct(v,total)}</td></tr>)}</tbody></table>}</section>}
export default function Analytics(){
  const [days,setDays]=useState(7),[internal,setInternal]=useState(false),[report,setReport]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
  useEffect(()=>{let cancelled=false;setLoading(true);setReport(null);setError('');(async()=>{
    try{const {data}=await supabase.auth.getSession();if(!data.session)throw Error('Sign in with your administrator account to view this report.');
    const r=await fetch(`/api/analytics/report?days=${days}&internal=${internal}`,{headers:{Authorization:`Bearer ${data.session.access_token}`}});const body=await r.json();if(!r.ok)throw Error(body.error);if(!cancelled)setReport(body);
    }catch(e){if(!cancelled)setError(e.message);}finally{if(!cancelled)setLoading(false);}
  })();return()=>{cancelled=true;};},[days,internal,refresh]);
  const t=report?.totals;
  return <main className="min-h-screen bg-stone-50 text-stone-800 p-5 md:p-10"><Head><title>Homepage analytics | MindMirror3D</title><meta name="robots" content="noindex,nofollow"/></Head><div className="max-w-6xl mx-auto"><Link href="/" className="underline">Homepage</Link><h1 className="text-3xl font-semibold mt-6">Homepage behavior</h1><p className="my-3">Unique visits with recorded homepage views. A visit expires after 30 minutes without an event. These are observed actions, not proof of intent.</p><div className="flex flex-wrap gap-5 items-center my-6"><label>Period <select className="border rounded p-2" value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,7,14,30,90].map(d=><option key={d} value={d}>{d} days</option>)}</select></label><label><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Include test traffic</label><button className="border rounded p-2" onClick={()=>setRefresh(n=>n+1)}>Refresh</button></div>
  {loading&&<p>Loading report…</p>}{error&&<div role="alert" className="bg-amber-50 border p-5">{error} <Link className="underline" href="/auth">Sign in</Link></div>}
  {report&&<>{report.truncated&&<p role="alert">Report reached the 50,000-event limit. Choose a shorter period; these totals are incomplete.</p>}<p className="text-sm mb-5">{internal?'Test traffic included.':`${report.excludedTestEvents} test events excluded.`} Section reach means its heading entered view. Active time counts visible-tab time, not verified reading.</p>
  <div className="grid md:grid-cols-4 gap-4 mb-6">{[['Homepage visits',t.visits],['Active ≥10 seconds',t.engaged],['Preview-click visits',t.clicked],['Profile arrivals',t.profile]].map(([label,value])=><div className="bg-white border p-5 rounded-xl" key={label}><p>{label}</p><strong className="text-3xl">{value}</strong></div>)}</div>
  <div className="bg-stone-800 text-white rounded-xl p-6 mb-6"><h2 className="text-xl">Main experiment metric: {pct(t.engagedClicked,t.engaged)}</h2><p>{t.engagedClicked} engaged visits clicked a preview button / {t.engaged} engaged visits.</p><p className="mt-3">All-visit preview conversion: {pct(t.clicked,t.visits)} · Homepage-to-profile: {pct(t.profile,t.visits)}</p></div>
  <div className="grid md:grid-cols-2 gap-5">{[['Section reach',report.sections],['How It Works cards viewed',report.cards],['Symbols explored',report.symbols],['Preview button location',report.buttons],['Booklet pages viewed',report.pages],['Furthest booklet page',report.depth],['Video viewing',report.video]].map(([title,values])=><Table key={title} title={title} values={values} total={t.visits}/>)}</div>
  <section className="bg-white border rounded-xl p-5 mt-6 overflow-auto"><h2 className="text-xl font-semibold mb-4">Device, version and campaign comparisons</h2><table className="w-full text-left text-sm"><thead><tr><th>Segment</th><th>Visits</th><th>Preview clicks</th><th>Profile arrivals</th></tr></thead><tbody>{Object.entries(report.segments).map(([key,v])=><tr key={key} className="border-t"><td className="py-3">{key}</td><td>{v.visits}</td><td>{pct(v.clicked,v.visits)}</td><td>{pct(v.profile,v.visits)}</td></tr>)}</tbody></table></section></>}
  </div></main>;
}
